# Generated by Django 5.0.7 on 2024-10-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В процессе'), ('delivery', 'Доставка'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('ready', 'Готово')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
