# Generated by Django 5.0.7 on 2024-10-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий курьера'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_photos/', verbose_name='Фото доставки'),
        ),
    ]
