# Generated by Django 5.0.7 on 2024-10-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промо Код', 'verbose_name_plural': 'Промо Коды'},
        ),
    ]
