# Generated by Django 5.0.7 on 2024-10-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_promocode_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
    ]
