# Generated by Django 5.0.7 on 2024-10-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_promo_code'),
        ('product', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='topping',
            field=models.ManyToManyField(blank=True, to='product.topping', verbose_name='Добавки'),
        ),
    ]
