# Generated by Django 5.0.7 on 2024-10-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_telegrambottoken_bot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentcashback',
            name='min_order_price',
            field=models.IntegerField(null=True, verbose_name='Минимальная сумма заказа'),
        ),
    ]
