# Generated by Django 5.0.7 on 2024-10-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_percentcashback_min_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentcashback',
            name='min_order_price',
            field=models.IntegerField(default=1, verbose_name='Минимальная сумма заказа'),
            preserve_default=False,
        ),
    ]
