# Generated by Django 5.0.7 on 2024-10-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_percentcashback_min_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancepricing',
            name='distance',
            field=models.IntegerField(verbose_name='Расстояние (м)'),
        ),
        migrations.AlterField(
            model_name='distancepricing',
            name='price',
            field=models.IntegerField(verbose_name='Время (мин)'),
        ),
    ]
