# Generated by Django 5.0.7 on 2024-11-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_distancepricing_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='partial_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Частичная оплата бонусами'),
        ),
    ]
