# Generated by Django 5.0.7 on 2024-11-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_partial_bonus_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentcashback',
            name='bonus_to_use',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальный процент покрытия бонусами(%)'),
        ),
    ]
