# Generated by Django 5.0.7 on 2024-11-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_percentcashback_bonus_to_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentcashback',
            name='bonus_to_use',
            field=models.IntegerField(default=1, verbose_name='Максимальный процент покрытия бонусами(%)'),
            preserve_default=False,
        ),
    ]
