# Generated by Django 5.0.7 on 2024-11-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_percentcashback_bonus_to_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentcashback',
            name='payment_card',
            field=models.BooleanField(default=True, verbose_name='Оплата онлайн'),
        ),
        migrations.AddField(
            model_name='percentcashback',
            name='payment_cash',
            field=models.BooleanField(default=True, verbose_name='Оплата наличными'),
        ),
    ]
