# Generated by Django 5.0.7 on 2024-11-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_percentcashback_payment_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pg_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
