# Generated by Django 5.0.7 on 2024-11-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_pg_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pg_payment_id',
            new_name='payment_id',
        ),
    ]
