# Generated by Django 5.0.7 on 2024-11-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentcashback',
            name='delivery',
            field=models.BooleanField(default=True, verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='percentcashback',
            name='pick_up',
            field=models.BooleanField(default=True, verbose_name='Самовывоз'),
        ),
    ]
