# Generated by Django 5.0.7 on 2024-11-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_percentcashback_delivery_percentcashback_pick_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='Статус Оплаты'),
        ),
    ]
