# Generated by Django 5.0.7 on 2024-11-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Оплачено'), ('failed', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус Оплаты'),
        ),
    ]
