# Generated by Django 5.0.7 on 2024-09-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Углеводы (граммы)'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Жиры (граммы)'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Белки (граммы)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Срок хранения'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Условия хранения'),
        ),
    ]
