# Generated by Django 5.0.7 on 2024-09-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_carbohydrates_product_composition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kkal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ккал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Углеводы (граммы)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Жиры (граммы)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Белки (граммы)'),
        ),
    ]
