# Generated by Django 5.0.7 on 2024-10-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productsize_quantity_productsize_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='unit',
            field=models.CharField(choices=[('kg', 'Килограммы'), ('g', 'Граммы'), ('l', 'Литры'), ('ml', 'Миллилитры'), ('pcs', 'Штуки')], default='pcs', max_length=5, verbose_name='Единица измерения'),
        ),
    ]
