# Generated by Django 5.0.7 on 2024-10-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productsize_quantity_alter_productsize_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(max_length=255, verbose_name='Размер'),
        ),
    ]
