# Generated by Django 5.0.7 on 2024-10-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('g', 'гр'), ('l', 'л'), ('ml', 'мл'), ('pcs', 'шт')], default='pcs', max_length=5, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('g', 'гр'), ('l', 'л'), ('ml', 'мл'), ('pcs', 'шт')], default='pcs', max_length=5, verbose_name='Единица измерения'),
        ),
    ]
