# Generated by Django 5.0.7 on 2024-10-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_quantity_product_unit_alter_productsize_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, max_length=255, verbose_name='Размер'),
        ),
    ]
