# Generated by Django 5.0.7 on 2024-10-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
    ]
