# Generated by Django 5.0.7 on 2024-10-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_quantity_alter_productsize_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10, verbose_name='Количество'),
        ),
    ]
