# Generated by Django 5.0.7 on 2024-10-23 07:24

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenientFunctionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Раздел Удобный Функционал',
                'verbose_name_plural': 'Раздел Удобный Функционал',
            },
        ),
        migrations.CreateModel(
            name='MainPageSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(help_text='Иконка для главной страницы.', upload_to='site_icon/', verbose_name='Логотип')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/meta', verbose_name='Изображение')),
                ('download_text', models.CharField(help_text='Скачать приложение сейчас', max_length=255, verbose_name='Текст')),
                ('google_play_icon', models.FileField(upload_to='site_icon/', verbose_name='Иконка для Google Play')),
                ('google_play_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('app_store_icon', models.FileField(upload_to='site_icon/', verbose_name='Иконка для Google Play')),
                ('app_store_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета описание')),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='images/meta', verbose_name='Мета изображение')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='site_icon/', verbose_name='Изображение продукта')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продукта',
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('question', models.TextField(blank=True, help_text='Что вы найдете в нашем приложении?', null=True, verbose_name='Поле для вопроса?')),
            ],
            options={
                'verbose_name': 'Особенность сервиса',
                'verbose_name_plural': 'Особенности сервиса',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/static', verbose_name='Изображение')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета описание')),
                ('meta_image', models.FileField(blank=True, null=True, upload_to='images/meta', verbose_name='Мета изображение')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
            },
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='site_icon/', verbose_name='Изображение продукта')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тэг')),
                ('text_color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='Цвет текста')),
                ('background_color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='Цвет фона')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Основная цена')),
                ('discounted_price', models.IntegerField(verbose_name='Скидочная цена')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ConvenientFunctionalityChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/static', verbose_name='Изображение')),
                ('qr_image', models.FileField(blank=True, null=True, upload_to='images/static', verbose_name='Qr Изображение')),
                ('qr_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('convenient_functionality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.convenientfunctionality', verbose_name='Удобный Функционал')),
            ],
            options={
                'verbose_name': 'Подраздел Удобный Функционал',
                'verbose_name_plural': 'Подраздел Удобный Функционал',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('icon', models.FileField(upload_to='payment_icons')),
                ('main_page_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.mainpagesite')),
            ],
            options={
                'verbose_name': 'Ссылка для оплаты',
                'verbose_name_plural': 'Ссылки для оплаты',
            },
        ),
        migrations.CreateModel(
            name='ServiceFeatureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='site_icon/', verbose_name='Иконка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('service_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.servicefeature', verbose_name='Особенность сервиса')),
            ],
            options={
                'verbose_name': 'Раздел Этап обслуживания',
                'verbose_name_plural': 'Раздел Этап обслуживания',
            },
        ),
    ]
