# Generated by Django 5.0.7 on 2024-10-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagesite',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='mainpagesite',
            name='app_store_icon',
            field=models.FileField(upload_to='site_icon/', verbose_name='Иконка для App Store'),
        ),
    ]
