# Generated by Django 5.0.7 on 2024-10-23 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_mainpagesite_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landing.product', verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
