# Generated by Django 5.0.7 on 2024-10-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_subproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название продукта'),
            preserve_default=False,
        ),
    ]
