# Generated by Django 5.0.7 on 2024-10-23 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='landing.product', verbose_name='Продукт'),
        ),
    ]
