# Generated by Django 5.0.7 on 2024-10-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_subproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenientfunctionalitychapter',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='images/static', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='convenientfunctionalitychapter',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='images/static', verbose_name='Изображение 3'),
        ),
    ]
