# Generated by Django 5.0.7 on 2024-10-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='icon',
            field=models.ImageField(help_text='Иконка для главной страницы.', upload_to='images/icons', verbose_name='Логотип'),
        ),
    ]
