# Generated by Django 5.0.7 on 2024-10-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_mainpage_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paybox_url', models.URLField(verbose_name='Paybox URL')),
                ('merchant_id', models.CharField(max_length=100, verbose_name='Merchant ID')),
                ('merchant_secret', models.CharField(max_length=100, verbose_name='Merchant Secret')),
                ('merchant_secret_payout', models.CharField(max_length=100, verbose_name='Merchant Secret Payout')),
            ],
            options={
                'verbose_name': 'Payment Setting',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
