# Generated by Django 5.0.7 on 2024-10-29 11:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_smssettings_alter_paymentsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
    ]
